### ISSUE TITLE
Issues with GUI 

### ISSUE THREAD

**Issue by voicecomms** [tarikogut/JasminWebPanel#13]
Hello There again, I managed to install your JasminWebPanel on top of Jasmin it starts perfectly but gives me the below error 
TelnetUnexpectedResponse: Unexpected response from Jasmin

logs

[09/Jun/2018 16:44:09] "GET /administration/users/ HTTP/1.1" 200 19020
[09/Jun/2018 16:44:09] "GET /static/assets/css/bootstrap.min.css HTTP/1.1" 304 0
[09/Jun/2018 16:44:09] "GET /static/assets/css/animate.min.css HTTP/1.1" 304 0
[09/Jun/2018 16:44:09] "GET /static/assets/css/light-bootstrap-dashboard.css HTTP/1.1" 304 0
[09/Jun/2018 16:44:09] "GET /static/assets/css/pe-icon-7-stroke.css HTTP/1.1" 304 0
[09/Jun/2018 16:44:09] "GET /static/assets/js/jquery-1.10.2.js HTTP/1.1" 304 0
[09/Jun/2018 16:44:09] "GET /static/assets/js/bootstrap.min.js HTTP/1.1" 304 0
[09/Jun/2018 16:44:10] "GET /static/assets/js/light-bootstrap-dashboard.js HTTP/1.1" 304 0
[09/Jun/2018 16:44:10] "GET /static/administration/js/users.js HTTP/1.1" 304 0
Internal Server Error: /administration/users/manage/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/src/JasminWebPanel-master/main/apps/administration/views/users.py", line 20, in users_view_manage
    tc = TelnetConnection()
  File "/usr/src/JasminWebPanel-master/main/apps/core/smpp/conn.py", line 13, in __init__
    raise TelnetUnexpectedResponse
TelnetUnexpectedResponse: Unexpected response from Jasmin
Internal Server Error: /administration/groups/manage/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/src/JasminWebPanel-master/main/apps/administration/views/groups.py", line 20, in groups_view_manage
    tc = TelnetConnection()
  File "/usr/src/JasminWebPanel-master/main/apps/core/smpp/conn.py", line 13, in __init__
    raise TelnetUnexpectedResponse
TelnetUnexpectedResponse: Unexpected response from Jasmin
Exception AttributeError: AttributeError("'TelnetConnection' object has no attribute 'telnet'",) in <bound metho                                                        d TelnetConnection.__del__ of <main.apps.core.smpp.conn.TelnetConnection object at 0x7fcf01913dd0>> ignored
Exception AttributeError: AttributeError("'TelnetConnection' object has no attribute 'telnet'",) in <bound metho                                                        d TelnetConnection.__del__ of <main.apps.core.smpp.conn.TelnetConnection object at 0x7fcf0189c890>> ignored
[09/Jun/2018 16:44:10] "POST /administration/groups/manage/ HTTP/1.1" 500 16128
[09/Jun/2018 16:44:10] "POST /administration/users/manage/ HTTP/1.1" 500 15959
[09/Jun/2018 16:44:11] "GET /static/assets/img/sidebar-2.jpg HTTP/1.1" 200 129997
[09/Jun/2018 16:44:12] "GET /administration/users/ HTTP/1.1" 200 19020
Internal Server Error: /administration/groups/manage/

any help appreciated, Thanks in advance.

Best Regards 
Chetan Jha

**Comment by voicecomms** [comment]
Hello Now I am getting the below output 

Internal Server Error: /administration/smppccm/manage/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/src/JasminWebPanel-master/main/apps/administration/views/smppccm.py", line 32, in smppccm_view_manage
    "password": request.POST.get("password"),
  File "/usr/src/JasminWebPanel-master/main/apps/core/smpp/smppccm.py", line 135, in create
    self.telnet.expect(r'.*' + STANDARD_PROMPT)
  File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 315, in expect
    timeout, searchwindowsize, async)
  File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 339, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python2.7/dist-packages/pexpect/expect.py", line 104, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python2.7/dist-packages/pexpect/expect.py", line 68, in timeout
    raise TIMEOUT(msg)
TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7f6be0655ed0>

please help 

Regards 
Chetan Jha

**Comment by jyotikmayur7** [comment]
how did you solve the first error.
I'm getting that too
Any help would be highly appretated

**Comment by voicecomms** [comment]
Hello, 
Delete all the existing files.
unzip it again, check for permissions & repeat all the install process it should work.



Best Regards 
Chetan jha

**Comment by voicecomms** [comment]
Hello, It should work and it is not that complicated setup, 
btw which OS are you using? 
Regards 
CJ

**Comment by voicecomms** [comment]
let me know if you can share your remote session in case you need remote assistance for help. team viewer or any desk?

Regards
CJ

**Comment by jyotikmayur7** [comment]
ubuntu

**Comment by jyotikmayur7** [comment]
Yes, i share it on team viewer

**Comment by jyotikmayur7** [comment]
@voicecomms it would be great help if you can share your email id with me so i can directly mail you about the problem.

**Comment by voicecomms** [comment]
chetang.jha@gmail.com ---- On Thu, 28 Jun 2018 15:00:31 +0530 Jyotik Mayur <notifications@github.com> wrote ---- @voicecomms it would be great help if you can share your email id with me so i can directly mail you about the problem. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by voicecomms** [comment]
All resolved, UI working fine 
@jyotikmayur7 be courteous to share a word of thanks for assistance provided.

Regards 
CJ

**Comment by navkarjain** [comment]
Hello @voicecomms it would be great if you could share your solution here on the thread.
